### ISSUE TITLE
Does not support Linux Mint which is a Debian based distro

### ISSUE THREAD

**Issue by alexaandru** [simonkberg/atom-check-updates#2]
```
$ acu
  ✨ atom-check-updates v0.0.2 ✨   

Retrieving information about your distro...
You don't seem to be running a supported distro
```

If it works on Ubuntu should work seamlessly on Linux Mint as well.

**Comment by simonkberg** [comment]
Thanks for reporting, it should indeed work fine so I'll do some investigation. Meanwhile, could you send me the output of `which dpkg` and `/usr/bin/dpkg --search /usr/bin/dpkg` respectively?

**Comment by simonkberg** [comment]
Also, what mint flavor (cinnamon, mate, kde, etc) and version are you on?

**Comment by alexaandru** [comment]
``` Bash
$ lsb_release -d
Description:    Linux Mint 17.3 Rosa
$ which dpkg
/usr/bin/dpkg
$ /usr/bin/dpkg --search /usr/bin/dpkg
dpkg: /usr/bin/dpkg
```

I am using the Mate version.

Thank you :)

**Comment by simonkberg** [comment]
Thanks, I booted up a virtual box, but sadly I'm not able to reproduce.

``` sh
$ lsb_release -d
Description:    Linux Mint 17.3 Rosa
$ acu
  ✨ atom-check-updates v0.0.2 ✨   

Retrieving information about your distro...
- Detected as running on a Debian-based distro. 
...
```

The response from `/usr/bin/dpkg --search /usr/bin/dpkg` also tells me the check should have passed. Could you tell me what version of node and npm you're using?

**Comment by alexaandru** [comment]
Sure: 

```
$ node -v
v0.10.25
$ npm -v
1.3.10
```

**Comment by alexaandru** [comment]
I've upgrade to:

```
$ nodejs -v
v5.10.1
$ npm -v
3.8.3
```

and it all works now :) Can't believe I had such an old version (I do keep my system up to date).

Thanks again!

**Comment by simonkberg** [comment]
No problem, glad that solved it :)
